#!/bin/bash

# compile the 3rd parties (modules)
# =======================
git submodule init
git submodule update --remote
cd thirdParty

# MoorDyn v1
echo "compile MoorDyn v1"
cd MoorDyn_v1/compileSO
make -j
cp -f MoorDyn.so $FOAM_USER_LIBBIN/libmoordynv1.so
#cp -f ../MoorDyn.h $FOAM_USER_LIBBIN/../include/MoorDynv1.h
cp -f ../MoorDyn.h $WM_PROJECT_USER_DIR/foamMooring/src/include/MoorDynv1.h
cd ../..

# MoorDyn v2
echo "compile MoorDyn v2"
mkdir MoorDyn.build
cd MoorDyn.build
cmake -DBUILD_TESTING=OFF -DEXTERNAL_EIGEN=OFF -DFORTRAN_WRAPPER=OFF -DMATLAB_WRAPPER=OFF -DPYTHON_WRAPPER=OFF -DCMAKE_BUILD_TYPE=Release -DCMAKE_INSTALL_PREFIX=$FOAM_USER_LIBBIN/.. ../MoorDyn
make -j
make install
cd ..

# compile MAP++

# compile Moody

cd ..

# compile MAP++
echo "compile MAP++"
(cd map-plus-plus/src; make && cp libmap-1.30.00.so $FOAM_USER_LIBBIN)

# copy precompiled Moody library
cp moody-2.0.1-Linux/lib/libmoody.so $FOAM_USER_LIBBIN

# compile sixDoFRigidBodyMotionRestraints
echo "compile mooring restraints"
( cd src/sixDoFMooringRestraints && wmake libso )

echo "Compilation done!"
