#!/bin/bash

# MoorDyn v1
(cd thirdParty/MoorDyn_v1/compileSO; make clean)

# MoorDyn v2
rm –r $FOAM_USER_LIBBIN/cmake  
rm –r $FOAM_USER_LIBBIN/../include 
rm -rf thirdParty/MoorDyn.build

# compile MAP++
(cd map-plus-plus/src; make clean)

# copy precompiled Moody library
#cp moody-2.0.1-Linux/lib/libmoody.so $FOAM_USER_LIBBIN

# compile sixDoFRigidBodyMotionRestraints
( cd src/sixDoFMooringRestraints && wclean )

echo "Compilation clean!"
