# Generated by CMake

if("${CMAKE_MAJOR_VERSION}.${CMAKE_MINOR_VERSION}" LESS 2.5)
   message(FATAL_ERROR "CMake >= 2.6.0 required")
endif()
cmake_policy(PUSH)
cmake_policy(VERSION 2.6)
#----------------------------------------------------------------
# Generated CMake target import file.
#----------------------------------------------------------------

# Commands may need to know the format version.
set(CMAKE_IMPORT_FILE_VERSION 1)

# Protect against multiple inclusion, which would fail when already imported targets are added once more.
set(_targetsDefined)
set(_targetsNotDefined)
set(_expectedTargets)
foreach(_expectedTarget MoorDyn::moordyn)
  list(APPEND _expectedTargets ${_expectedTarget})
  if(NOT TARGET ${_expectedTarget})
    list(APPEND _targetsNotDefined ${_expectedTarget})
  endif()
  if(TARGET ${_expectedTarget})
    list(APPEND _targetsDefined ${_expectedTarget})
  endif()
endforeach()
if("${_targetsDefined}" STREQUAL "${_expectedTargets}")
  unset(_targetsDefined)
  unset(_targetsNotDefined)
  unset(_expectedTargets)
  set(CMAKE_IMPORT_FILE_VERSION)
  cmake_policy(POP)
  return()
endif()
if(NOT "${_targetsDefined}" STREQUAL "")
  message(FATAL_ERROR "Some (but not all) targets in this export set were already defined.\nTargets Defined: ${_targetsDefined}\nTargets not yet defined: ${_targetsNotDefined}\n")
endif()
unset(_targetsDefined)
unset(_targetsNotDefined)
unset(_expectedTargets)


# Create imported target MoorDyn::moordyn
add_library(MoorDyn::moordyn SHARED IMPORTED)

set_target_properties(MoorDyn::moordyn PROPERTIES
  COMPATIBLE_INTERFACE_STRING "moordyn_MAJOR_VERSION"
  INTERFACE_COMPILE_DEFINITIONS "MoorDyn_EXPORTS"
  INTERFACE_INCLUDE_DIRECTORIES "/home/hfchen/OpenFOAM/hfchen-v2012/foamMooring/modules/MoorDyn.build/source;/home/hfchen/OpenFOAM/hfchen-v2012/foamMooring/modules/MoorDyn/source"
  INTERFACE_moordyn_MAJOR_VERSION "2"
)

# Import target "MoorDyn::moordyn" for configuration "Release"
set_property(TARGET MoorDyn::moordyn APPEND PROPERTY IMPORTED_CONFIGURATIONS RELEASE)
set_target_properties(MoorDyn::moordyn PROPERTIES
  IMPORTED_LOCATION_RELEASE "/home/hfchen/OpenFOAM/hfchen-v2012/foamMooring/modules/MoorDyn.build/source/libmoordyn.so.2.0"
  IMPORTED_SONAME_RELEASE "libmoordyn.so.2"
  )

# This file does not depend on other imported targets which have
# been exported from the same project but in a separate export set.

# Commands beyond this point should not need to know the version.
set(CMAKE_IMPORT_FILE_VERSION)
cmake_policy(POP)
